name: hungry
description: A travel diary, for you and your friends

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0

  firebase_core: 1.17.0

  cloud_firestore: 3.1.15

  firebase_auth: 3.3.18
  google_sign_in: 5.3.1
  
  intl: 
  
  camera:
  path_provider:
  path:

  uuid: 3.0.6

  image_picker: ^0.8.5+3
  flutter_sound: ^9.2.12
  audioplayers: ^0.20.1
  permission_handler: ^9.2.0
  mime: ^1.0.2

  flutter_map: ^0.14.0
  flutter_map_marker_cluster: 0.4.4
  latlong2: ^0.8.1
  geolocator: 8.2.1

  cached_network_image: ^3.2.1
  flutter_cache_manager: ^3.3.0
  firebase_storage: ^10.2.16

  exif: ^3.1.1

  gallery_saver: 2.3.2
  dio: 4.0.5
  carousel_slider: ^4.1.1
  photo_view: ^0.14.0
  share_plus: ^4.0.4
  http: 
  async: ^2.8.2
  rxdart: ^0.27.4
  audio_session: ^0.1.7
  animated_text_kit: ^4.2.2
  flutter_compass: ^0.7.0
  geoflutterfire: ^3.0.3
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
    - family: Open Sans
      fonts:
        - asset: assets/fonts/open sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/open sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open sans/OpenSans-ExtraBold.ttf
          weight: 800
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
