// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'firebase_options.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 




class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdnbXIqm6gc0_5hwWJC-TIF05yP7tklAc',
    appId: '1:768756834625:web:bf84f41296b6dc4d5901c0',
    messagingSenderId: '768756834625',
    projectId: 'wanderic',
    authDomain: 'wanderic.firebaseapp.com',
    storageBucket: 'wanderic.appspot.com',
    measurementId: 'G-KXL4E07MS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw_nDBL_AkqmN3977NCnVGgffpIrqIaf8',
    appId: '1:768756834625:android:01e957baf2175d5f5901c0',
    messagingSenderId: '768756834625',
    projectId: 'wanderic',
    storageBucket: 'wanderic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4cXjk2DEku4_MraklVe9aGjz-ciR_8s0',
    appId: '1:768756834625:ios:02a51b242f2a69005901c0',
    messagingSenderId: '768756834625',
    projectId: 'wanderic',
    storageBucket: 'wanderic.appspot.com',
    iosClientId: '768756834625-i3eenogoppfev0g6beag8f7ci6jjfae8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hungry',
  );
}
